### ISSUE TITLE
Automate zarf version updates

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-zarf-init#242]
This project appears to be using a fairly [old version](https://github.com/defenseunicorns/delivery-zarf-init/pkgs/container/delivery-zarf-init%2Finit) of the zarf init package. This could cause issues with newer zarf cli versions.

**Comment by mcamick** [comment]
@ntwkninja this should be resolved with the credential fixes and it looks to be back in working order, closing the issue.
